name: Build Windows Game
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Installa Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Abilita Desktop
        run: flutter config --enable-windows-desktop

      - name: Installa dipendenze
        run: flutter pub get

      - name: Costruisci EXE
        run: flutter build windows --release

      - name: Comprimi i file (Zip)
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath SmartChips_Windows.zip

      - name: Carica il risultato
        uses: actions/upload-artifact@v4
        with:
          name: Gioco-Windows
          path: SmartChips_Windows.zip
